In [1]:
from sklearn.datasets import make_classification
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.model_selection import cross_val_score

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

%matplotlib inline

Повечето операции в NumPy работят с така наречената векторизация. Това по-лесно се илюстрира с пример:

In [3]:
np.array([1, 2, 3, 4]) * 5

array([ 5, 10, 15, 20])

In [4]:
np.array([1, 2, 3]) * np.array([3, 4, 5])

array([ 3,  8, 15])

In [6]:
np.array([8, 3, 4, 1, 9, 4]) > 4

array([ True, False, False, False,  True, False])

In [7]:
(np.array([8, 3, 4, 1, 9, 4]) > 4).astype(float)

array([1., 0., 0., 0., 1., 0.])